---
title: "SLAM-Seq mapping statistics (SLAM-seq test)"
author: "Inés Rivero-García"
date: "03/18/2026"
output: 
  html_document:
    theme: cerulean
    number_sections: true
    toc: yes
    toc_float:
      collapsed: true
---

```{r setup}
library(ggplot2)
library(dplyr)

# set project root for the notebook
knitr::opts_knit$set(root.dir = "/Volumes/INTENSO/PhD/cardio_slamseq/")

data_path <- "data"
aligned_reads_path <- file.path(data_path, "Aligned.Reads")
fig_path  <- "figures/01_preprocessing/STAR_stats"
```

```{r prep_data}
metadata <- read.csv(
  file.path(data_path, "metadata.csv"),
  header = TRUE,
  stringsAsFactors = FALSE
)

metadata_batch0 <- metadata[metadata$Experimental_batch == 0, , drop = FALSE]

sample_levels <- metadata_batch0 %>% pull(Sample)

find_star_log <- function(sample_name) {
  matching_files <- list.files(
    aligned_reads_path,
    pattern = paste0("^", sample_name, "_.*Log\\.final\\.out$"),
    full.names = TRUE
  )

  if (length(matching_files) != 1) {
    stop("Expected exactly one STAR log for sample '", sample_name, "', found ", length(matching_files),".")
  }

  return(matching_files)
}

parse_star_log <- function(log_file) {
  log_table <- read.delim(
    log_file,
    sep = "|",
    header = FALSE,
    stringsAsFactors = FALSE,
    fill = TRUE,
    strip.white = TRUE,
    quote = ""
  )

  metric_names <- trimws(log_table[[1]])
  metric_values <- trimws(log_table[[2]])
  stats <- setNames(metric_values, metric_names)

  parse_number <- function(metric_name) {
    as.numeric(gsub("%", "", stats[[metric_name]], fixed = TRUE))
  }

  data.frame(
    Nr_reads = parse_number("Number of input reads"),
    Nr_uniquely_mapped_reads = parse_number("Uniquely mapped reads number"),
    Percent_uniquely_mapped_reads = parse_number("Uniquely mapped reads %"),
    Nr_multimapping_reads = parse_number("Number of reads mapped to multiple loci"),
    Percent_multimapping_reads = parse_number("% of reads mapped to multiple loci"),
    Nr_reads_mapping_too_many_loci = parse_number("Number of reads mapped to too many loci"),
    Percent_reads_mapping_too_many_loci = parse_number("% of reads mapped to too many loci"),
    Nr_unmaped_reads_mismatches = parse_number("Number of reads unmapped: too many mismatches"),
    Percent_unmapped_reads_mismatches = parse_number("% of reads unmapped: too many mismatches"),
    Nr_unmaped_reads_short = parse_number("Number of reads unmapped: too short"),
    Percent_unmapped_reads_short = parse_number("% of reads unmapped: too short"),
    Nr_unmapped_reads_other = parse_number("Number of reads unmapped: other"),
    Percent_unmapped_reads_other = parse_number("% of reads unmapped: other"),
    Percent_mismatch_per_base = parse_number("Mismatch rate per base, %"),
    stringsAsFactors = FALSE
  )
}

df <- do.call(
  rbind,
  lapply(sample_levels, function(sample_name) {
    sample_stats <- parse_star_log(find_star_log(sample_name))
    data.frame(
      Sample = sample_name,
      sample_stats,
      stringsAsFactors = FALSE
    )
  })
)

colors <- c("#BBBBBB", "#FA8072", "#FF0800", "#420D09")
names(colors) <- sample_levels

df$Sample <- factor(df$Sample, levels = sample_levels)
df <- df[order(df$Sample), ]
```

# Alignment statistics (STAR)
```{r nrRawReads}
nr_reads_plt <- ggplot(df, aes(x = Sample,
                               y = Nr_reads/10^6,
                               fill = Sample,
                               color = Sample)) +
  geom_bar(stat = "identity", width = 0.5) +
  theme_classic() +
  scale_fill_manual(values = colors) +
  scale_color_manual(values = colors) +
  scale_y_continuous(limits = c(0, 160), 
                     breaks = c(0, 25, 50, 75, 100, 125, 150)) +
  xlab("") +
  ylab("Number of raw reads (Millions)") +
  theme(legend.position = "none")

pdf(file.path(fig_path, "AlignedReads_SlamSeqTest_NrRawReads.pdf"), width = 3, height = 3)
nr_reads_plt
dev.off()

nr_reads_plt
```
```{r UniquelyMappedReads}
nr_uniqmap_plt <- ggplot(df, aes(x = Sample,
                                 y = Nr_uniquely_mapped_reads/10^6,
                                 fill = Sample,
                                 color = Sample)) +
  geom_bar(stat = "identity", width = 0.5) +
  theme_classic() +
  scale_fill_manual(values = colors) +
  scale_color_manual(values = colors) +
  scale_y_continuous(limits = c(0, 160), 
                     breaks = c(0, 25, 50, 75, 100, 125, 150)) +
  xlab("") +
  ylab("Nr uniquely mapped reads (Millions)") +
  theme(legend.position = "none")

pdf(file.path(fig_path, "AlignedReads_SlamSeqTest_NrUniquelyMappingReads.pdf"), width = 3, height = 3)
nr_uniqmap_plt
dev.off()

nr_uniqmap_plt
```

```{r UniquelyMappedReadsPercent}
pct_uniqmap_plt <- ggplot(df, aes(x = Sample,
                                  y = Percent_uniquely_mapped_reads,
                                  fill = Sample,
                                  color = Sample)) + 
  geom_bar(stat = "identity", width = 0.5) +
  theme_classic() +
  scale_fill_manual(values = colors) +
  scale_color_manual(values = colors) +
  scale_y_continuous(limits = c(0, 100), 
                     breaks = c(0, 20, 40, 60, 80, 100)) +
  xlab("") +
  ylab("Percentage of uniquely mapped reads") +
  theme(legend.position = "none")

pdf(file.path(fig_path, "AlignedReads_SlamSeqTest_PercentageUniquelyMappingReads.pdf"), width = 3, height = 3)
pct_uniqmap_plt
dev.off()

pct_uniqmap_plt
```
```{r MultiMappedReads}
nr_multimap_plt <- ggplot(df, aes(x = Sample,
                                  y = Nr_multimapping_reads/10^6,
                                  fill = Sample,
                                  color = Sample)) + 
  geom_bar(stat = "identity", width = 0.5) +
  theme_classic() +
  scale_fill_manual(values = colors) +
  scale_color_manual(values = colors) +
  scale_y_continuous(limits = c(0, 15), 
                     breaks = c(0, 5, 10, 15)) +
  xlab("") +
  ylab("Nr multi-mapping reads (Millions)") +
  theme(legend.position = "none")

pdf(file.path(fig_path, "AlignedReads_SlamSeqTest_NrMultimappingReads.pdf"), width = 3, height = 3)
nr_multimap_plt
dev.off()

nr_multimap_plt
```
```{r MultiMappedReadsPercent}
pct_multimap_plt <- ggplot(df, aes(x = Sample, 
                                   y = Percent_multimapping_reads, 
                                   fill = Sample, 
                                   color = Sample)) + 
  geom_bar(stat = "identity", width = 0.5) +
  theme_classic() +
  scale_fill_manual(values = colors) +
  scale_color_manual(values = colors) +
  scale_y_continuous(limits = c(0, 10), 
                     breaks = c(0, 2, 4, 6, 8, 10)) +
  xlab("") +
  ylab("Percentage of multi-mapping reads") +
  theme(legend.position = "none")

pdf(file.path(fig_path, "AlignedReads_SlamSeqTest_PercentageMultimappingReads.pdf"), width = 3, height = 3)
pct_multimap_plt
dev.off()

pct_multimap_plt
```
```{r TooManyLoci}
nr_manyloci_plt <- ggplot(df, aes(x = Sample,
                                  y = Nr_reads_mapping_too_many_loci/10^6,
                                  fill = Sample,
                                  color = Sample)) + 
  geom_bar(stat = "identity", width = 0.5) +
  theme_classic() +
  scale_fill_manual(values = colors) +
  scale_color_manual(values = colors) +
  scale_y_continuous(limits = c(0, 1), 
                     breaks = c(0, 0.2, 0.4, 0.6, 0.8, 1)) +
  xlab("") +
  ylab("Nr unmapped reads (too many loci) (Millions)") +
  theme(legend.position = "none")

pdf(file.path(fig_path, "AlignedReads_SlamSeqTest_NrReadsTooManyLoci.pdf"), width = 3, height = 3)
nr_manyloci_plt
dev.off()

nr_manyloci_plt
```
```{r TooManyLociPercentage}
pct_manyloci_plt <- ggplot(df, aes(x = Sample,
                                   y = Percent_reads_mapping_too_many_loci,
                                   fill = Sample,
                                   color = Sample)) + 
  geom_bar(stat = "identity", width = 0.5) +
  theme_classic() +
  scale_fill_manual(values = colors) +
  scale_color_manual(values = colors) +
  scale_y_continuous(limits = c(0, 1), 
                     breaks = c(0, 0.2, 0.4, 0.6, 0.8, 1)) +
  xlab("") +
  ylab("Percentage of unmapped reads\n(too many loci)") +
  theme(legend.position = "none")

pdf(file.path(fig_path, "AlignedReads_SlamSeqTest_PercentageReadsTooManyLoci.pdf"), width = 3, height = 3)
pct_manyloci_plt
dev.off()

pct_manyloci_plt
```
```{r MismatchesUnmapped}
nr_mismatch_plt <- ggplot(df, aes(x = Sample,
                                  y = Nr_unmaped_reads_mismatches/10^6,
                                  fill = Sample,
                                  color = Sample)) + 
  geom_bar(stat = "identity", width = 0.5) +
  theme_classic() +
  scale_fill_manual(values = colors) +
  scale_color_manual(values = colors) +
  scale_y_continuous(limits = c(0, 1.03), 
                     breaks = c(0, 0.2, 0.4, 0.6, 0.8, 1)) +
  xlab("") +
  ylab("Nr unmapped reads\n(too many mismatches) (Millions)") +
  theme(legend.position = "none")

pdf(file.path(fig_path, "AlignedReads_SlamSeqTest_NrReadsTooManyMismatches.pdf"), width = 3, height = 3)
nr_mismatch_plt
dev.off()

nr_mismatch_plt
```
```{r MismatchesUnmappedPercent}
pct_mismatch_plt <- ggplot(df, aes(x = Sample,
                                   y = Percent_unmapped_reads_mismatches,
                                   fill = Sample,
                                   color = Sample)) + 
  geom_bar(stat = "identity", width = 0.5) +
  theme_classic() +
  scale_fill_manual(values = colors) +
  scale_color_manual(values = colors) +
  scale_y_continuous(limits = c(0, 1), 
                     breaks = c(0, 0.2, 0.4, 0.6, 0.8, 1)) +
  xlab("") +
  ylab("Percentage of unmapped reads\n(too many mismatches)") +
  theme(legend.position = "none")

pdf(file.path(fig_path, "AlignedReads_SlamSeqTest_PercentageReadsTooManyMismatches.pdf"), width = 3, height = 3)
pct_mismatch_plt
dev.off()

pct_mismatch_plt
```
```{r ShortUnmapped}
nr_short_plt <- ggplot(df, aes(x = Sample,
                               y = Nr_unmaped_reads_short/10^6,
                               fill = Sample,
                               color = Sample)) + 
  geom_bar(stat = "identity", width = 0.5)+
  theme_classic() +
  scale_fill_manual(values = colors) +
  scale_color_manual(values = colors) +
  scale_y_continuous(limits = c(0,3), 
                     breaks = c(0, 0.5, 1, 1.5, 2, 2.5, 3)) +
  xlab("") +
  ylab("Nr unmapped reads\n(too short) (Millions)") +
  theme(legend.position = "none")

pdf(file.path(fig_path, "AlignedReads_SlamSeqTest_NrReadsTooShort.pdf"),width = 3, height = 3)
nr_short_plt
dev.off()

nr_short_plt
```
```{r ShortUnmappedPercent}
pct_short_plt <- ggplot(df, aes(x = Sample,
                                y = Percent_unmapped_reads_short,
                                fill = Sample,
                                color = Sample)) + 
  geom_bar(stat = "identity", 
           width = 0.5) +
  theme_classic() +
  scale_fill_manual(values = colors) +
  scale_color_manual(values = colors) +
  scale_y_continuous(limits = c(0, 2), 
                     breaks = c(0, 0.5, 1, 1.5, 2)) +
  xlab("") +
  ylab("Percentage of unmapped reads\n(too short)") +
  theme(legend.position = "none")

pdf(file.path(fig_path, "AlignedReads_SlamSeqTest_PercentageReadsTooShort.pdf"), width = 3, height = 3)
pct_short_plt
dev.off()

pct_short_plt
```
```{r OtherUnmapped}
nr_otherunamp_plt <- ggplot(df, aes(x = Sample, 
                               y = Nr_unmapped_reads_other/10^6,
                               fill = Sample,
                               color = Sample)) + 
  geom_bar(stat = "identity", width = 0.5) +
  theme_classic() +
  scale_fill_manual(values = colors) +
  scale_color_manual(values = colors) +
  xlab("") +
  ylab("Nr unmapped reads\n(other reasons) (Millions)") +
  theme(legend.position = "none")

pdf(file.path(fig_path, "AlignedReads_SlamSeqTest_NrReadsUnmappedOtherReasons.pdf"), width = 3, height = 3)
nr_otherunamp_plt
dev.off()

nr_otherunamp_plt
```
```{r OtherUnmappedPercent}
pct_otherunmapped_plt <- ggplot(df, aes(x = Sample,
                                        y = Percent_unmapped_reads_other, 
                                        fill = Sample, 
                                        color = Sample)) + 
  geom_bar(stat = "identity", width = 0.5) +
  theme_classic() +
  scale_fill_manual(values = colors) +
  scale_color_manual(values = colors) +
  xlab("") +
  ylab("Percentage of unmapped reads\n(other reasons)") +
  theme(legend.position = "none")

pdf(file.path(fig_path, "AlignedReads_SlamSeqTest_PercentageReadsUnmappedOtherReasons.pdf"), width = 3, height = 3)
pct_otherunmapped_plt
dev.off()

pct_otherunmapped_plt
```
```{r StackedNrReads}
Stacked_Reads_DF <- df[, c("Sample", 
                           "Nr_uniquely_mapped_reads", 
                           "Nr_multimapping_reads",
                           "Nr_reads_mapping_too_many_loci",
                           "Nr_unmaped_reads_mismatches",
                           "Nr_unmaped_reads_short",
                           "Nr_unmapped_reads_other")]
Stacked_Reads_DF <- reshape2::melt(Stacked_Reads_DF)

nr_reads_plt <- ggplot(Stacked_Reads_DF, aes(x = Sample, 
                                             y = value, 
                                             fill = variable)) + 
  geom_bar(position = "stack", stat = "identity", width = 0.5) +
  theme_classic() +
  coord_flip() +
  scale_fill_brewer(palette = "Purples", 
                    direction = -1,
                    labels = c("Uniquely mapping", 
                               "Multi-mapping",
                               "Unmaped: too many loci",
                               "Unmaped: too many mismatches",
                               "Unmapped: too short",
                               "Unmapped: other reasons")) +
  ylab("Number of reads (Millions)") +
  theme(legend.position = "right")

pdf(file.path(fig_path, "AlignedReads_SlamSeqTest_NrReadsPerCategory.pdf"), width = 5, height = 3)
nr_reads_plt
dev.off()

nr_reads_plt
```
```{r StackedNrReadsPercent}
pct_reads_plt <- ggplot(Stacked_Reads_DF, aes(x = Sample, 
                                              y = value,
                                              fill = variable)) + 
  geom_bar(position = "fill", stat = "identity", width = 0.5) +
  theme_classic() +
  coord_flip() +
  scale_fill_brewer(palette = "Purples", 
                    direction = -1,
                    labels = c("Uniquely mapping", 
                               "Multi-mapping",
                               "Unmaped: too many loci",
                               "Unmaped: too many mismatches",
                               "Unmapped: too short",
                               "Unmapped: other reasons")) +
  ylab("Proportion of reads") +
  theme(legend.position = "right")

pdf(file.path(fig_path, "AlignedReads_SlamSeqTest_PercentageReadsPerCategory.pdf"), width = 5, height = 3)
pct_reads_plt
dev.off()

pct_reads_plt
```
```{r MismatchPerBase}
mismatches_plt <- ggplot(df, aes(x = Sample,
                                 y = Percent_mismatch_per_base,
                                 fill = Sample,
                                 color = Sample)) + 
  geom_bar(stat = "identity", width = 0.5) +
  theme_classic() +
  scale_fill_manual(values = colors) +
  scale_color_manual(values = colors) +
  scale_y_continuous(limits = c(0,2)) +
  xlab("") +
  ylab("% mismatches per nucleotide") +
  theme(legend.position = "none")

pdf(file.path(fig_path, "AlignedReads_SlamSeqTest_MismatchRatePerBase.pdf"),width = 3, height = 3)
mismatches_plt
dev.off()

mismatches_plt
```
